### ISSUE TITLE
How do I define duration for each slide. I see there only global options set for all the slide. Thanks much

### ISSUE THREAD

**Issue by wdshahin** [mdgriffin/pogo-slider#14]

**Comment by mdgriffin** [comment]
Each slide can be configured individually to have a different slide duration using the `data-duration` property.

**Comment by wdshahin** [comment]
Thank you for replying. 
I meant the duration to display each of the slides. Not to be confused with elementTransitionDuration / data-duration 

I hope you understand.

**Comment by mdgriffin** [comment]
Sorry, yes I understand now. You are right, it can only be set globally using `autoplayTimeout` option.

**Comment by wdshahin** [comment]
Any future update fixing this / or any quick way to do it?

Regards.
