### ISSUE TITLE
Element animation start time before slide transition

### ISSUE THREAD

**Issue by Barcante** [mdgriffin/pogo-slider#15]
Hi,

I couldn't set the elements animation to begin before the slide changes. My objective is to the elements fade out and I can see the image in the back for a few ms before it changes to the next slide.

Thanks a lot.

**Comment by mdgriffin** [comment]
I think you can achieve that using your own CSS animation with the fade out completing at an earlier percentage (like 75%). Custom animations are set using the `data-in` and `data-out` properties, the class names need to be prefixed with `.pogoSlider-animation-`
